### ISSUE TITLE
timerfd_gettime is not defined

### ISSUE THREAD

**Issue by arrowd** [jiixyj/epoll-shim#12]
pipewire master branch started using `timerfd_gettime` function, which is `#if 0`ed for some reason. If it is hard to implement, can we at least provide a stub for it?

While there, `timerfd.h` is also not defining `TFD_TIMER_CANCEL_ON_SET`, which is used in `timerfd_settime` call.

**Comment by jiixyj** [comment]
I've stubbed out `timerfd_gettime` in the branch "12-timerfd-gettime". Hopefully that part of pipewire will compile now. It looks like nothing really uses this call, though. Same thing with `TFD_TIMER_CANCEL_ON_SET`. So maybe stubbing them out will be enough.

In any case, `timerfd_gettime` doesn't look too difficult to implement.

`TFD_TIMER_CANCEL_ON_SET` looks like a different beast...

**Comment by arrowd** [comment]
This allowed me to build pipewire master. Can't test it yet, though, but is compiles, at least.

**Comment by jiixyj** [comment]
I've merged the "12-timerfd-gettime" branch (stub implementation) into master. For the "real" implementation of `timerfd_gettime` I've opened issue https://github.com/jiixyj/epoll-shim/issues/13.
