### ISSUE TITLE
cmake failure

### ISSUE THREAD

**Issue by DyslexicAtheist** [jiixyj/epoll-shim#22]
Hi,

following the installation instructions from README.md results in:

```
cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo
CMake Error at test/CMakeLists.txt:20 (add_library):
  add_library cannot create target "epoll-shim" because another target with
  the same name already exists.  The existing target is a shared library
  created in source directory "/home/da/src/epoll-shim/src".  See
  documentation for policy CMP0002 for more details.

```

**Comment by jiixyj** [comment]
Thanks for the report! Are you building this under Linux? In that case, only the tests will build. You have to specify the `test` folder as CMake's source directory.

So in your case `cmake ../test -DCMAKE_BUILD_TYPE=RelWithDebInfo` should work (after clearing the build folder).

The library itself will only build when compiling under FreeBSD, NetBSD, OpenBSD or DragonFlyBSD. I admit the error message could be better, though...

**Comment by jiixyj** [comment]
If anyone wants to build the tests on Linux, this can be done now from the top level directory as usual with CMake. The library will not be built of course.
