### ISSUE TITLE
Why return EPOLLHUP on not yet connected stream sockets?

### ISSUE THREAD

**Issue by sghctoma** [jiixyj/epoll-shim#3]
Hello,

Commit 7a36cd3f36c04dcd1f32004d2038f9491664df19 introduced a change to return `EPOLLHUP` on not yet connected stream sockets. Is it really the desirable behaviour? As per the Linux man page, `epoll` should share the same semantics as `poll` when used in the default level-triggered mode, and `poll` does not do this. The Linux version of `epoll` does not do it either. Consider the following program:

```c
#include <stdio.h>
#include <stdlib.h>
#ifdef __FreeBSD__
#include <malloc_np.h>
#endif
#include <unistd.h>
#include <sys/epoll.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <string.h>


int main(int argc, char** argv)
{
	struct sockaddr_un *sockaddr = malloc(sizeof(struct sockaddr_un));
	sockaddr->sun_family = AF_UNIX;

	int path_size = sizeof(sockaddr->sun_path);
	snprintf(sockaddr->sun_path, path_size, "/tmp/epoll-test.sock");
	unlink(sockaddr->sun_path);

	int sock = socket(AF_UNIX, SOCK_STREAM, 0);
	bind(sock, (struct sockaddr *)sockaddr, sizeof(*sockaddr));
	listen(sock, 3);

	int epoll_fd = epoll_create1(EPOLL_CLOEXEC);
	struct epoll_event ep;
	memset(&ep, 0, sizeof ep);
	ep.events = EPOLLIN;
	epoll_ctl(epoll_fd, EPOLL_CTL_ADD, sock, &ep);

	struct epoll_event events[1] = {0};
	epoll_wait(epoll_fd, events, 1, -1);
	printf("ep[0].events=%d\n", events[0].events);
}
```

This will block until an incoming connection (`EPOLLIN` event) on Linux, but return immediately on FreeBSD, becauase an `EPOLLHUP` was received. The equivalent program that uses `poll` blocks on both Linux and FreeBSD:

```c
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <poll.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <string.h>


int main(int argc, char** argv)
{
	struct sockaddr_un *sockaddr = malloc(sizeof(struct sockaddr_un));
	sockaddr->sun_family = AF_UNIX;

	int path_size = sizeof(sockaddr->sun_path);
	snprintf(sockaddr->sun_path, path_size, "/tmp/epoll-test.sock");
	unlink(sockaddr->sun_path);

	int sock = socket(AF_UNIX, SOCK_STREAM, 0);
	bind(sock, (struct sockaddr *)sockaddr, sizeof(*sockaddr));
	listen(sock, 3);

	struct pollfd fds[1];
	fds[0].fd = sock;
	fds[0].events = POLLIN;
	int p = poll(fds, 1, -1);
	printf("fds[0].revents=%d\n", fds[0].revents);
}
```

This behaviour causes trouble with sway, because it waits for a `WL_EVENT_READABLE` Wayland event to detect incoming connections on a socket (it is fired when an `EPOLLIN` event happens on the socket), and gets `EPOLLHUP` immediately instead.

**Comment by jiixyj** [comment]
Thanks for the report! You are right, if `bind()` and `listen()` were called we must not return `EPOLLHUP` but wait for incoming connections. The `EPOLLHUP` special handling is for the case where `bind()` and `listen()` haven't been called yet, i.e. we start calling `epoll_wait` on a fresh socket.

**Comment by sghctoma** [comment]
I see, it makes sense now. Thanks for the quick fix, it seems to be working as expected now.

It took a bit longer than expected for me to confirm that this works with sway, because I've run into another problem, for which I'll open an issue in a moment.

**Comment by jiixyj** [comment]
This should be fixed in master.
