### ISSUE TITLE
Ignore EVFILT_WRITE deregistration ENOENT errors

### ISSUE THREAD

**Issue by sghctoma** [jiixyj/epoll-shim#4]
In src/epoll.c at line 293, `EVFILT_WRITE` registration `EINVAL` errors are ignored. If you register an fd, and this happens, you won't be able to deregister it, because trying to remove the nonexistent `EVFILT_WRITE` filter will result in error `ENOENT`, and `epoll_ctl` will return -1 at line 299.

I have replaced line 293 with the following:

```c
if (i == 1 && (kev[i].data == EINVAL || kev[i].data == ENOENT)) {
```

The reason I opened an issue, and not sent a pull request is that I'm not 100% sure if this is the correct thing to do, but it seems to work with sway now.

**Comment by jiixyj** [comment]
Thank you! Your fix looks correct to me.

**Comment by sghctoma** [comment]
Cool, thanks for adding the fix!
I have yet another problem that occurs when using the latest epoll-shim (input is lost in sway  when switching TTYs). I had no time to investigate it yet, so I don't know if it's related to either this, or #3. I have a 4-day weekend ahead, I'll try to come up with something.

**Comment by jiixyj** [comment]
I guess this can be closed.
