### ISSUE TITLE
Support eventfd

### ISSUE THREAD

**Issue by myfreeweb** [jiixyj/epoll-shim#6]
This would be required for [pipewire](https://github.com/PipeWire/pipewire)

**Comment by jiixyj** [comment]
Good idea, this should not be too hard to implement with something like `NOTE_TRIGGER`.

**Comment by arrowd** [comment]
Funny thing - I started porting pipewire and stumbled upon this very PR. Any chance you'll implement this in near future, @jiixyj ?

And @myfreeweb , do you have workings on pipewire somewhere in flight?

**Comment by myfreeweb** [comment]
I have some small patches for an old revision at home, nothing very interesting but I'll check when I get home

**Comment by jiixyj** [comment]
I'm currently playing around with implementing `eventfd`, stay tuned...

**Comment by jiixyj** [comment]
Please check out branch https://github.com/jiixyj/epoll-shim/tree/6-eventfd.

I've found some eventfd tests from another project (https://github.com/jiixyj/epoll-shim/blob/6-eventfd/test/tst-eventfd.c) and they all work except for POLLOUT (i.e. checking if an eventfd is writable). eventfd is implemented with a kqueue fd + NOTE_TRIGGER, so only POLLIN works. But this should be enough for all major use cases I guess.

**Comment by arrowd** [comment]
Using your allowed me significantly advance in pipewire porting, but I still can't finish it and run-test it. I'll come back once I get something to report.

**Comment by arrowd** [comment]
I finished porting pipewire and it does even seem to work. Thanks for your work!

Now it would be awesome, if you upstream your changes and we update the `epoll-shim` port.

**Comment by jiixyj** [comment]
Good to hear! Could you re-test with the current master branch? I've refactored the library internals a bit to remove some hacks and for easier maintenance.

I've update the current port here for testing: https://github.com/jiixyj/freebsd-ports/tree/libepoll-shim/devel/libepoll-shim . I'll contact the port maintainers :)

**Comment by jiixyj** [comment]
I've opened an issue at the port maintainer's repo here: https://github.com/FreeBSDDesktop/epoll-shim/issues/4

**Comment by jiixyj** [comment]
I guess we can close this issue here for now. Please let me know and create additional issues if you encounter any problems with the `eventfd`s.
